SELECT 
F.INTEGRATION_ID,
MT.MODE_OF_TRANSPORT, 
ESDT.MCAL_DAY_DT EST_TL_SHIP_DT,
DP.EST_SHIP_DATE_TL AS DOMPROY_TL,
CASE
  WHEN ESDT.MCAL_DAY_CODE = '__NOT_APPLICABLE__'
  THEN NULL ELSE ESDT.MCAL_DAY_CODE END AS EST_TL_SHIP_DAY,
ESDL.MCAL_DAY_DT EST_LTL_SHIP_DT,
DP.EST_SHIP_DATE_LTL AS DPOMROY_LTL,
CASE
  WHEN ESDL.MCAL_DAY_CODE = '__NOT_APPLICABLE__'
  THEN NULL ELSE ESDL.MCAL_DAY_CODE END AS EST_LTL_SHIP_DAY,
PD.MCAL_DAY_DT PRED_SHIP_DT,
DP.PREDICTED_SHIP_DATE_NO_POOLING AS DPOMROY_PREDICTED,
PD.MCAL_DAY_DT - DP.PREDICTED_SHIP_DATE_NO_POOLING AS DATEDIFFERENCE
FROM
WC_SALES_GLOBAL_ORDER_F F,
WVC_CUST_SHIP_TO_D C,
WC_MODE_OF_TRANSPORT_D MT,
W_MCAL_DAY_D OD,
W_STATUS_D S,
W_MCAL_DAY_D ESDT,
W_MCAL_DAY_D ESDL,
W_MCAL_DAY_D SD,
W_MCAL_DAY_D SSD,
W_MCAL_DAY_D RD,
W_MCAL_DAY_D PD,
WVC_PRODUCT_D I,
W_INT_ORG_D O,
DPOMROY.USR_CD_CUST_PROD_DAY_PIPE_PSD DP
WHERE F.DATASOURCE_NUM_ID = 9000
AND F.INTEGRATION_ID = DP.INTEGRATION_ID
AND F.CUSTOMER_SHIP_TO_LOC_WID = C.ROW_WID
AND C.BUSINESS_UNIT = 'CPG'
AND F.MODE_OF_TRANSPORT_WID = MT.ROW_WID
AND F.ORDERED_ON_DT_WID = OD.MCAL_DAY_DT_WID
AND OD.X_MCAL_YR_PER_NAME_CAL_MNTH = '2017 P 04 JAN'
AND F.ORDER_STATUS_WID = S.ROW_WID
AND S.STATUS_CODE <> 'CLOSED'
AND F.EST_TL_SHIP_DT_WID = ESDT.MCAL_DAY_DT_WID
AND F.EST_LTL_SHIP_DT_WID = ESDL.MCAL_DAY_DT_WID
AND F.ACT_LAST_SHIPPED_ON_DT_WID = SD.MCAL_DAY_DT_WID
AND F.CSD_LAST_SHIP_ON_DT_WID = SSD.MCAL_DAY_DT_WID
AND F.REQUIRED_BY_DT_WID = RD.MCAL_DAY_DT_WID
AND F.PREDICTED_SHIP_DT_WID = PD.MCAL_DAY_DT_WID
AND F.PRODUCT_WID = I.ROW_WID
AND F.INVENTORY_ORG_WID = O.SCD1_WID
AND PD.MCAL_DAY_DT != DP.PREDICTED_SHIP_DATE_NO_POOLING
ORDER BY 5;




SELECT * FROM DPOMROY.USR_CD_CUST_PROD_DAY_PIPE_PSD

FROM APPBAW_DW.WC_SALES_GLOBAL_ORDER_F WC
    JOIN DPOMROY.USR_CD_CUST_PROD_DAY_PIPE_PSD DP
        ON WC.INTEGRATION_ID = DP.INTEGRATION_ID
    

    
    
SELECT WC.INTEGRATION_ID, DP.INTEGRATION_ID, WC.PREDICTED_SHIP_DT_WID, DP.PREDICTED_SHIP_DATE_NO_POOLING
    FROM APPBAW_DW.WC_SALES_GLOBAL_ORDER_F WC
        JOIN DPOMROY.USR_CD_CUST_PROD_DAY_PIPE_PSD DP
            ON WC.INTEGRATION_ID = DP.INTEGRATION_ID

    
